### PR TITLE
Added Lecture 02: TDD

### PR DESCRIPTION
**Pull request by mwand**
In Slides/ and Examples/     Comments?

### CODE REVIEW

**Comment by iamabhutta** [comment]
Suggest updating names of instructors

**Comment by mwand** [comment]
instructor names updated.

**Comment by jon-bell** [comment]
Looks great! I fixed a few typos on the slides. The example has a stale README.md from an old async activity - is there anything else besides what's on slide 26 that should go into that README?

**Comment by iamabhutta** [comment]
readme file talk about async stuff which isn't covered till later. We should update the readme file.

**Comment by iamabhutta** [comment]
You might need to add link to activity starter code?

**Comment by jon-bell** [comment]
Who is the "you" directed at? I'm not sure how we settled on distributing the link to the starter code

**Comment by iamabhutta** [comment]
I guess it would be @mwand {but if you are helping setup the resources for the first time, then it could be you @jon-bell :) }. I guess we should first discuss/update/finalize the activity starter code and instructions ....

**Comment by mwand** [comment]
> is there anything else besides what's on slide 26 that should go into that README?

> readme file talk about async stuff which isn't covered till later. We should update the readme file.

What readme file are we talking about here?  The README in the zip for the activity (at Activities/Lesson 04*.zip) seems fine to me-- it's a tiny update from Jon's version from S21 or thereabouts.

**Comment by iamabhutta** [comment]
The learning objective in readme.md file that I found in tdd-transcipt-activity.zip under the most recent commit of "lecture2-tdd" branch is not the most recent one. It still talks abour async stuff

**Comment by iamabhutta** [comment]
did u move the wrong one? wasn't the correct one in "Activities" ??

**Comment by mwand** [comment]
that is entirely possible.   Did somebody rewrite the README, and if so,
where is it? :(

**Pull request merged**
