### PR TITLE
First draft of lecture05-Async

### PR DESCRIPTION
**Pull request by mwand**
Uploaded first draft of Async lecture.  Slides are pretty much complete, but I haven't updated the scripts to match.   Code for examples is in /Examples.

### CODE REVIEW

**Comment by jon-bell** [comment]
Looks great overall!

A few small comments:
* Slide 3 shows the graphic overlaid on the bullets
* Slide 7 shows how a computation is suspended, but I think it is also useful to say something about how the next computation is selected to run, even if it's "NodeJS determines" (key is that your code can't choose - it's up to the runtime)
* Slide 8 callout build text is hard to read on top of bullets - maybe set a solid background for it?
* Slide 8 should probably say something like "Using the async keyword implicitly changes the return type to be a Promise for whatever the return type was otherwise"
* What about the other ways that async programming can be implemented in JS - with callbacks, and with promise.then - should we mention these at all, or is it unnecessary technical detail?
* I think that it might be useful to also include an example of where adding "async" and "await" do not really change the behavior of the program - and show that there is only ever one computation running at a time.

**Comment by mwand** [comment]
On Mon, Aug 22, 2022 at 10:17 AM Jonathan Bell ***@***.***>
wrote:

> Looks great overall!
>
> A few small comments:
>
>    - Slide 3 shows the graphic overlaid on the bullets
>
> Animation fixed (and improved)

>
>    - Slide 7 shows how a computation is suspended, but I think it is also
>    useful to say something about how the next computation is selected to run,
>    even if it's "NodeJS determines" (key is that your code can't choose - it's
>    up to the runtime)
>
> I wrote:  A computation is suspended when it hits an ‘await’. The runtime
system (node.js, for us) chooses what to do next. (In addition to whatever
asynchronous IO it may be doing).

I think the last parenthetical is important

I wrote:

>
>    - Slide 8 callout build text is hard to read on top of bullets - maybe
>    set a solid background for it?
>
> Improved.

>
>    - Slide 8 should probably say something like "Using the async keyword
>    implicitly changes the return type to be a Promise for whatever the return
>    type was otherwise"
>
> No, saying async function makeOneGetRequest (req): void throws a type
error.

>
>    - What about the other ways that async programming can be implemented
>    in JS - with callbacks, and with promise.then - should we mention these at
>    all, or is it unnecessary technical detail?
>
> I've made a conscious choice to omit this material.  The couple of examples
 give enough of a flavor, I think.

**Comment by jon-bell** [comment]
These changes look great. As a minor point: did you mean to add a fourth bullet on slide 6 after "always run to completion:"?

To clarify on these:
> What about the other ways that async programming can be implemented in JS - with callbacks, and with promise.then - should we mention these at all, or is it unnecessary technical detail?

What I meant is: Do we mention the existence of other async programming constructs besides async/await, and the fact that an async method always returns a promise?

> I think that it might be useful to also include an example of where adding "async" and "await" do not really change the behavior of the program - and show that there is only ever one computation running at a time.

I was thinking along the lines of an example that shows that there is never more than a single handler running at the same time. As I try to think about it more, though, I am having a hard time describing this or coming up with a concrete example so I'm going to drop it.

**Comment by mwand** [comment]
>These changes look great. As a minor point: did you mean to add a fourth bullet on slide 6 after "always run to completion:"?

Nope, it continues on the next slide.  I've deleted the misleading colon.

>What about the other ways that async programming can be implemented in JS - with callbacks, and with promise.then - should we mention these at all, or is it unnecessary technical detail?
>What I meant is: Do we mention the existence of other async programming constructs besides async/await, and the fact that an async method always returns a promise?

Yes, see slides 29-31.  I couldn't figure out how to incorporate this into the main narrative, so I demoted it to  "Additional Topics ".  The lesson is already quite long.

>I think that it might be useful to also include an example of where adding "async" and "await" do not really change the behavior of the program - and show that there is only ever one computation running at a time.

>I was thinking along the lines of an example that shows that there is never more than a single handler running at the same time. As I try to think about it more, though, I am having a hard time describing this or coming up with a concrete example so I'm going to drop it.

I added this statement explicitly in Slide 7.   It gets used in the critical section example (slide 35)

**Comment by jon-bell** [comment]
Great! This all LGTM, then.

**Review by jon-bell — APPROVED** [review]

**Comment by mwand** [comment]
Merge when ready, Gridley.

**Pull request merged**
