### PR TITLE
Continuous development

### PR DESCRIPTION
**Pull request by jon-bell**

### CODE REVIEW

**Comment by iamabhutta** [comment]
slide 9 says HW3. It should be HW2, I think

**Comment by jon-bell** [comment]
I will change it to just say "Individual project" to be more future proof :)

**Comment by iamabhutta** [comment]
Few more minor comments: 
-Update heading of slide 21, its misleading. The point is that many bugs remains in system even after author reviewed it first. May be update the heading to "Peer reviews are still effective despite self-reviews" or "self reviews are no substitute for peer-reviews"
-font size in slide 23 is smaller than others
-Please add little more notes for last few slides (new ones, Usability testing)
-Slide 52 should be right after slide 30 but we can revisit it at the end too.

**Comment by iamabhutta** [comment]
I copied the above updates .... except these:
Slide 52 copied right after slide 30 (Done)
Please add little more notes for last few slides (new ones, Usability testing)

**Comment by iamabhutta** [comment]
I made the above updates .... including:
Slide 52 copied right after slide 30 (Done)
but not this:
Please add little more notes for last few slides (new ones, Usability testing)
rest lgtm
Good to merge!

**Pull request merged**
