### PR TITLE
Added folder Slides and Slides for Lecture1

### PR DESCRIPTION
**Pull request by iamabhutta**
Added slides and activities for lecture 1.

### CODE REVIEW

**Comment by mwand** [comment]
L1.1 S17 still mentions Gradescope

**Comment by mwand** [comment]
I count 42 slides for a 100 minute class.  That seems a bit much, especially if you're going to have an activity.  There's lots of redundancy between L1.1 and L1.2 .

I may push an edited version in this branch, depending on how much time I have.

**Comment by mwand** [comment]
Need to add a script with words for "DSS Accomodations for Group Assignment".

**Comment by mwand** [comment]
I am not very happy with the Backup Software Example.   What do you think about swapping in the College Administrator example from the TDD lesson?   That has the advantage of consistency across the lectures.

**Comment by jon-bell** [comment]
LGTM pending non-functional requirements slide. I will prepare the pages around the slides and have it ready from my side by Tuesday.

**Comment by iamabhutta** [comment]
@mwand please check slide # 15 (NF Requirements) for Lesson 1.2. Please update as needed. After that @jon-bell can publish the Week1 module. Thanks

**Comment by jon-bell** [comment]
Lecture page is added, preview at https://631614dee3e0e30008cb7703--effervescent-hotteok-7b489d.netlify.app/modules/1-requirements-testing

**Comment by iamabhutta** [comment]
lgtm

**Comment by mwand** [comment]
I tweaked the opening text on L1.2 S15.   The rest of the slide isn't actually phrased in terms of "requirements".   A non-functional  *requirement* might be something like "The system can handle 1000 requests per second with a median delay of 100 msecs."   But I think what's there is close enough.

lgtm now.

**Pull request merged**
