### PR TITLE
Lecture 4 design patterns

### PR DESCRIPTION
**Pull request by mwand**
Here is Lesson 4 (Design Patterns); slides, examples, activities

### CODE REVIEW

**Comment by jon-bell** [comment]
Would you please `git add` the file `Activities/week2-designpatterns-observer.zip`?

**Comment by mwand** [comment]
Fixed.  (Bad reference in .md file).

**Comment by mwand** [comment]
Two questions:
1.  Any further comments on content?
2.  This PR started failing checks several commits ago.   Does anybody know why?

**Comment by jon-bell** [comment]
The [latest deploy log](https://app.netlify.com/sites/effervescent-hotteok-7b489d/deploys/6312034d496ea100080bc101) shows:

> 9:21:52 AM:   Liquid Exception: Could not find document 'Activities/Lesson04 Activity (Weather Station).zip' in tag 'link'. Make sure the document exists and the path is correct. in Activities/Lesson04 Activity (Weather Station).md
> 9:21:52 AM: jekyll 3.9.0 | Error:  Could not find document 'Activities/Lesson04 Activity (Weather Station).zip' in tag 'link'.
> 9:21:52 AM: Make sure the document exists and the path is correct.
> 9:21:52 AM: /opt/build/cache/bundle/ruby/2.7.0/gems/jekyll-3.9.0/lib/jekyll/tags/link.rb:27:in `render': Could not find document 'Activities/Lesson04 Activity (Weather Station).zip' in tag 'link'. (ArgumentError)

I do not see the file `Lesson04 Activity (Weather Station).zip` committed in this PR.

**Comment by mwand** [comment]
Sounds like a spelling error.  I will track it down and make sure the
activity is spelled correctly and in the right place.   Also sounds like I
will have to look up again how to build the web page locally so I can avoid
this in the future.

**Comment by jon-bell** [comment]
I took a look at the slides, and I think that these are great!

I think that there might be at least one more learning objective for this material, though, something like: "Understand that patterns capture common solutions and tradeoffs for recurring problems." I think that this objective is already well-supported through the lesson, but perhaps adding one more slide after slide 11 re-summarizing the tradeoff between push/pull (producer knows the consumer interface vs consumer knows the producer interface; consumer checks every time they want the data to be updated vs producer notifies consumer when data is updated) would help set up the comparison between the two clock implementations and underscore the motivation for examining both examples.

**Comment by mwand** [comment]
Done.

**Review by jon-bell — APPROVED** [review]

**Pull request merged**
